// Country dialing codes
export const COUNTRY_DIALING_CODES = [
  { country: "Afghanistan", code: "AF", dial: "+93" },
  { country: "Albania", code: "AL", dial: "+355" },
  { country: "Algeria", code: "DZ", dial: "+213" },
  { country: "Andorra", code: "AD", dial: "+376" },
  { country: "Angola", code: "AO", dial: "+244" },
  { country: "Argentina", code: "AR", dial: "+54" },
  { country: "Armenia", code: "AM", dial: "+374" },
  { country: "Australia", code: "AU", dial: "+61" },
  { country: "Austria", code: "AT", dial: "+43" },
  { country: "Azerbaijan", code: "AZ", dial: "+994" },
  { country: "Bahrain", code: "BH", dial: "+973" },
  { country: "Bangladesh", code: "BD", dial: "+880" },
  { country: "Belarus", code: "BY", dial: "+375" },
  { country: "Belgium", code: "BE", dial: "+32" },
  { country: "Belize", code: "BZ", dial: "+501" },
  { country: "Benin", code: "BJ", dial: "+229" },
  { country: "Bhutan", code: "BT", dial: "+975" },
  { country: "Bolivia", code: "BO", dial: "+591" },
  { country: "Bosnia and Herzegovina", code: "BA", dial: "+387" },
  { country: "Botswana", code: "BW", dial: "+267" },
  { country: "Brazil", code: "BR", dial: "+55" },
  { country: "Brunei", code: "BN", dial: "+673" },
  { country: "Bulgaria", code: "BG", dial: "+359" },
  { country: "Burkina Faso", code: "BF", dial: "+226" },
  { country: "Burundi", code: "BI", dial: "+257" },
  { country: "Cambodia", code: "KH", dial: "+855" },
  { country: "Cameroon", code: "CM", dial: "+237" },
  { country: "Canada", code: "CA", dial: "+1" },
  { country: "Cape Verde", code: "CV", dial: "+238" },
  { country: "Central African Republic", code: "CF", dial: "+236" },
  { country: "Chad", code: "TD", dial: "+235" },
  { country: "Chile", code: "CL", dial: "+56" },
  { country: "China", code: "CN", dial: "+86" },
  { country: "Colombia", code: "CO", dial: "+57" },
  { country: "Comoros", code: "KM", dial: "+269" },
  { country: "Congo", code: "CG", dial: "+242" },
  { country: "Costa Rica", code: "CR", dial: "+506" },
  { country: "Croatia", code: "HR", dial: "+385" },
  { country: "Cuba", code: "CU", dial: "+53" },
  { country: "Cyprus", code: "CY", dial: "+357" },
  { country: "Czech Republic", code: "CZ", dial: "+420" },
  { country: "Denmark", code: "DK", dial: "+45" },
  { country: "Djibouti", code: "DJ", dial: "+253" },
  { country: "Dominican Republic", code: "DO", dial: "+1-809" },
  { country: "Ecuador", code: "EC", dial: "+593" },
  { country: "Egypt", code: "EG", dial: "+20" },
  { country: "El Salvador", code: "SV", dial: "+503" },
  { country: "Equatorial Guinea", code: "GQ", dial: "+240" },
  { country: "Eritrea", code: "ER", dial: "+291" },
  { country: "Estonia", code: "EE", dial: "+372" },
  { country: "Eswatini", code: "SZ", dial: "+268" },
  { country: "Ethiopia", code: "ET", dial: "+251" },
  { country: "Fiji", code: "FJ", dial: "+679" },
  { country: "Finland", code: "FI", dial: "+358" },
  { country: "France", code: "FR", dial: "+33" },
  { country: "Gabon", code: "GA", dial: "+241" },
  { country: "Gambia", code: "GM", dial: "+220" },
  { country: "Georgia", code: "GE", dial: "+995" },
  { country: "Germany", code: "DE", dial: "+49" },
  { country: "Ghana", code: "GH", dial: "+233" },
  { country: "Greece", code: "GR", dial: "+30" },
  { country: "Guatemala", code: "GT", dial: "+502" },
  { country: "Guinea", code: "GN", dial: "+224" },
  { country: "Guinea-Bissau", code: "GW", dial: "+245" },
  { country: "Guyana", code: "GY", dial: "+592" },
  { country: "Haiti", code: "HT", dial: "+509" },
  { country: "Honduras", code: "HN", dial: "+504" },
  { country: "Hungary", code: "HU", dial: "+36" },
  { country: "Iceland", code: "IS", dial: "+354" },
  { country: "India", code: "IN", dial: "+91" },
  { country: "Indonesia", code: "ID", dial: "+62" },
  { country: "Iran", code: "IR", dial: "+98" },
  { country: "Iraq", code: "IQ", dial: "+964" },
  { country: "Ireland", code: "IE", dial: "+353" },
  { country: "Israel", code: "IL", dial: "+972" },
  { country: "Italy", code: "IT", dial: "+39" },
  { country: "Jamaica", code: "JM", dial: "+1-876" },
  { country: "Japan", code: "JP", dial: "+81" },
  { country: "Jordan", code: "JO", dial: "+962" },
  { country: "Kazakhstan", code: "KZ", dial: "+7" },
  { country: "Kenya", code: "KE", dial: "+254" },
  { country: "Kuwait", code: "KW", dial: "+965" },
  { country: "Kyrgyzstan", code: "KG", dial: "+996" },
  { country: "Laos", code: "LA", dial: "+856" },
  { country: "Latvia", code: "LV", dial: "+371" },
  { country: "Lebanon", code: "LB", dial: "+961" },
  { country: "Lesotho", code: "LS", dial: "+266" },
  { country: "Liberia", code: "LR", dial: "+231" },
  { country: "Libya", code: "LY", dial: "+218" },
  { country: "Liechtenstein", code: "LI", dial: "+423" },
  { country: "Lithuania", code: "LT", dial: "+370" },
  { country: "Luxembourg", code: "LU", dial: "+352" },
  { country: "Madagascar", code: "MG", dial: "+261" },
  { country: "Malawi", code: "MW", dial: "+265" },
  { country: "Malaysia", code: "MY", dial: "+60" },
  { country: "Maldives", code: "MV", dial: "+960" },
  { country: "Mali", code: "ML", dial: "+223" },
  { country: "Malta", code: "MT", dial: "+356" },
  { country: "Mauritania", code: "MR", dial: "+222" },
  { country: "Mauritius", code: "MU", dial: "+230" },
  { country: "Mexico", code: "MX", dial: "+52" },
  { country: "Moldova", code: "MD", dial: "+373" },
  { country: "Monaco", code: "MC", dial: "+377" },
  { country: "Mongolia", code: "MN", dial: "+976" },
  { country: "Montenegro", code: "ME", dial: "+382" },
  { country: "Morocco", code: "MA", dial: "+212" },
  { country: "Mozambique", code: "MZ", dial: "+258" },
  { country: "Myanmar", code: "MM", dial: "+95" },
  { country: "Namibia", code: "NA", dial: "+264" },
  { country: "Nepal", code: "NP", dial: "+977" },
  { country: "Netherlands", code: "NL", dial: "+31" },
  { country: "New Zealand", code: "NZ", dial: "+64" },
  { country: "Nicaragua", code: "NI", dial: "+505" },
  { country: "Niger", code: "NE", dial: "+227" },
  { country: "Nigeria", code: "NG", dial: "+234" },
  { country: "North Korea", code: "KP", dial: "+850" },
  { country: "North Macedonia", code: "MK", dial: "+389" },
  { country: "Norway", code: "NO", dial: "+47" },
  { country: "Oman", code: "OM", dial: "+968" },
  { country: "Pakistan", code: "PK", dial: "+92" },
  { country: "Panama", code: "PA", dial: "+507" },
  { country: "Papua New Guinea", code: "PG", dial: "+675" },
  { country: "Paraguay", code: "PY", dial: "+595" },
  { country: "Peru", code: "PE", dial: "+51" },
  { country: "Philippines", code: "PH", dial: "+63" },
  { country: "Poland", code: "PL", dial: "+48" },
  { country: "Portugal", code: "PT", dial: "+351" },
  { country: "Qatar", code: "QA", dial: "+974" },
  { country: "Romania", code: "RO", dial: "+40" },
  { country: "Russia", code: "RU", dial: "+7" },
  { country: "Rwanda", code: "RW", dial: "+250" },
  { country: "Saudi Arabia", code: "SA", dial: "+966" },
  { country: "Senegal", code: "SN", dial: "+221" },
  { country: "Serbia", code: "RS", dial: "+381" },
  { country: "Seychelles", code: "SC", dial: "+248" },
  { country: "Sierra Leone", code: "SL", dial: "+232" },
  { country: "Singapore", code: "SG", dial: "+65" },
  { country: "Slovakia", code: "SK", dial: "+421" },
  { country: "Slovenia", code: "SI", dial: "+386" },
  { country: "Solomon Islands", code: "SB", dial: "+677" },
  { country: "Somalia", code: "SO", dial: "+252" },
  { country: "South Africa", code: "ZA", dial: "+27" },
  { country: "South Korea", code: "KR", dial: "+82" },
  { country: "South Sudan", code: "SS", dial: "+211" },
  { country: "Spain", code: "ES", dial: "+34" },
  { country: "Sri Lanka", code: "LK", dial: "+94" },
  { country: "Sudan", code: "SD", dial: "+249" },
  { country: "Suriname", code: "SR", dial: "+597" },
  { country: "Sweden", code: "SE", dial: "+46" },
  { country: "Switzerland", code: "CH", dial: "+41" },
  { country: "Syria", code: "SY", dial: "+963" },
  { country: "Taiwan", code: "TW", dial: "+886" },
  { country: "Tajikistan", code: "TJ", dial: "+992" },
  { country: "Tanzania", code: "TZ", dial: "+255" },
  { country: "Thailand", code: "TH", dial: "+66" },
  { country: "Togo", code: "TG", dial: "+228" },
  { country: "Trinidad and Tobago", code: "TT", dial: "+1-868" },
  { country: "Tunisia", code: "TN", dial: "+216" },
  { country: "Turkey", code: "TR", dial: "+90" },
  { country: "Turkmenistan", code: "TM", dial: "+993" },
  { country: "Uganda", code: "UG", dial: "+256" },
  { country: "Ukraine", code: "UA", dial: "+380" },
  { country: "United Arab Emirates", code: "AE", dial: "+971" },
  { country: "United Kingdom", code: "GB", dial: "+44" },
  { country: "United States", code: "US", dial: "+1" },
  { country: "Uruguay", code: "UY", dial: "+598" },
  { country: "Uzbekistan", code: "UZ", dial: "+998" },
  { country: "Venezuela", code: "VE", dial: "+58" },
  { country: "Vietnam", code: "VN", dial: "+84" },
  { country: "Yemen", code: "YE", dial: "+967" },
  { country: "Zambia", code: "ZM", dial: "+260" },
  { country: "Zimbabwe", code: "ZW", dial: "+263" },
];

// Ecosystem brands for TrustBar
export const ECOSYSTEM_BRANDS = [
  "ELCODERS",
  "EL SPACE",
  "ELITES",
  "ELACCESS",
  "NEXEL",
];

// FAQ items
export const FAQ_ITEMS = [
  {
    question: "What is EL SPACE?",
    answer: "EL SPACE is a premium freelancing platform built for serious professionals. It connects talented freelancers with clients seeking high-quality work, with built-in escrow protection, milestone tracking, and verified talent badges.",
    category: "client",
  },
  {
    question: "How does payment protection work?",
    answer: "All payments are held securely in escrow. Clients fund milestones upfront, and freelancers are paid when work is delivered and approved. This protects both parties and ensures fair transactions.",
    category: "client",
  },
  {
    question: "What are the fees?",
    answer: "We use a tiered pricing model. Clients pay a small service fee on top of project costs, and freelancers pay a competitive commission that decreases as they earn more. Check our pricing section for details.",
    category: "client",
  },
  {
    question: "How do I get verified?",
    answer: "Complete your profile, upload your portfolio, and pass our skills assessment test. Verified freelancers get a badge, higher visibility, and access to premium projects.",
    category: "freelancer",
  },
  {
    question: "How do I find projects?",
    answer: "Browse the job board, get matched through our smart algorithm, or be discovered by clients based on your skills and portfolio. Active freelancers with complete profiles get more opportunities.",
    category: "freelancer",
  },
  {
    question: "When do I get paid?",
    answer: "Once you deliver work and the client approves the milestone, funds are released from escrow to your wallet. You can then withdraw to your bank account within 2-3 business days.",
    category: "freelancer",
  },
  {
    question: "What if there's a dispute?",
    answer: "Our dispute resolution system ensures fair outcomes. Both parties can submit evidence, and our mediation team will review the case to reach a fair decision.",
    category: "freelancer",
  },
  {
    question: "Can I work with international clients?",
    answer: "Yes! EL SPACE supports global transactions with multiple payment methods and currency conversion. Work with clients and freelancers from anywhere in the world.",
    category: "freelancer",
  },
];

// Industries for clients
export const INDUSTRIES = [
  "Technology & Software",
  "Information Technology Services",
  "Financial Services & Banking",
  "Healthcare & Medical",
  "Education & Training",
  "E-commerce & Retail",
  "Manufacturing & Industrial",
  "Construction & Real Estate",
  "Media & Entertainment",
  "Marketing & Advertising",
  "Consulting & Professional Services",
  "Transportation & Logistics",
  "Food & Beverage",
  "Hospitality & Tourism",
  "Agriculture & Farming",
  "Energy & Utilities",
  "Telecommunications",
  "Legal Services",
  "Accounting & Tax Services",
  "Human Resources & Recruitment",
  "Design & Creative",
  "Architecture & Engineering",
  "Biotechnology & Pharmaceuticals",
  "Insurance",
  "Government & Public Administration",
  "Non-Profit & Social Services",
  "Sports & Fitness",
  "Fashion & Apparel",
  "Automotive",
  "Aerospace & Defense",
  "Environmental Services",
  "Publishing & Printing",
  "Arts & Culture",
  "Gaming & Esports",
  "Blockchain & Cryptocurrency",
  "Artificial Intelligence & Machine Learning",
  "Cybersecurity",
  "Cloud Computing & SaaS",
  "Data Analytics & Business Intelligence",
  "Other",
];

// Tech stacks for freelancers
export const TECH_STACKS = [
  // Frontend
  "React",
  "Next.js",
  "Vue.js",
  "Angular",
  "Svelte",
  "TypeScript",
  "JavaScript",
  "HTML/CSS",
  "Tailwind CSS",
  "Bootstrap",
  "SASS/SCSS",
  "Redux",
  "GraphQL",
  "REST APIs",
  
  // Backend
  "Node.js",
  "Express.js",
  "Python",
  "Django",
  "Flask",
  "FastAPI",
  "Java",
  "Spring Boot",
  "C#",
  ".NET",
  "PHP",
  "Laravel",
  "Ruby",
  "Ruby on Rails",
  "Go",
  "Rust",
  "Kotlin",
  "Scala",
  
  // Database
  "PostgreSQL",
  "MySQL",
  "MongoDB",
  "SQLite",
  "Redis",
  "Firebase",
  "Supabase",
  "DynamoDB",
  "Oracle",
  "SQL Server",
  
  // Cloud & DevOps
  "AWS",
  "Google Cloud",
  "Microsoft Azure",
  "Docker",
  "Kubernetes",
  "CI/CD",
  "Terraform",
  "Vercel",
  "Netlify",
  "Heroku",
  "DigitalOcean",
  
  // Mobile
  "React Native",
  "Flutter",
  "Swift",
  "Kotlin",
  "iOS Development",
  "Android Development",
  "Xamarin",
  
  // Design
  "Figma",
  "Adobe XD",
  "Photoshop",
  "Illustrator",
  "UI/UX Design",
  "Web Design",
  "Graphic Design",
  
  // Data Science & AI
  "Machine Learning",
  "Data Science",
  "TensorFlow",
  "PyTorch",
  "Pandas",
  "NumPy",
  "R Programming",
  "Computer Vision",
  "NLP",
  
  // Blockchain
  "Solidity",
  "Web3",
  "Ethereum",
  "Smart Contracts",
  "DeFi",
  
  // Testing
  "Jest",
  "Cypress",
  "Selenium",
  "Testing Library",
  "Mocha",
  
  // CMS
  "WordPress",
  "Shopify",
  "Contentful",
  "Strapi",
  "Sanity",
  
  // Other
  "Git",
  "Agile/Scrum",
  "Microservices",
  "System Design",
  "API Development",
  "WebSockets",
  "OAuth/JWT",
  "Payment Integration",
  "Stripe",
  "PayPal",
];

// Company sizes
export const COMPANY_SIZES = [
  "1-10 employees (Startup)",
  "11-50 employees (Small)",
  "51-200 employees (Medium)",
  "201-500 employees (Large)",
  "501-1000 employees (Enterprise)",
  "1000+ employees (Corporation)",
];

// Business types
export const BUSINESS_TYPES = [
  "Registered Business",
  "Starter Business",
  "Freelancer/Sole Proprietor",
  "Non-Profit Organization",
  "Government Agency",
  "Educational Institution",
];

// Experience levels
export const EXPERIENCE_LEVELS = [
  "Entry Level (0-2 years)",
  "Intermediate (2-5 years)",
  "Expert (5-10 years)",
  "Senior (10+ years)",
];

// Project categories
export const PROJECT_CATEGORIES = [
  "Web Development",
  "Mobile Development",
  "UI/UX Design",
  "Backend Development",
  "DevOps & Cloud",
  "Data Science & ML",
  "Blockchain",
  "Cybersecurity",
  "Quality Assurance",
  "Project Management",
  "Content Writing",
  "Digital Marketing",
  "Video & Animation",
  "Audio & Music",
  "Business Consulting",
  "Other",
];
